Event packet
UBC-Rocket/UBCRocketGroundStation pull request #55
Opened 2021-01-16 05:04 UTC by akoen

2021-01-17 01:07 UTC, DSep commented on main_window/packet_parser.py
> +# Matches enum EventId in FLARE: radio.h
If possible, might want to use the enum "DataEntryValues" in the data_entry_ids.py

2021-01-17 01:08 UTC, DSep commented on main_window/packet_parser.py
> +
If possible, might want to use the enum "DataEntryValues" in the data_entry_ids.py

2021-01-19 05:59 UTC, SilentSys requested changes
Looks great! Really digging the DataEntryValues renaming to make them more specific.

Just a few minor things.

2021-01-19 05:59 UTC, SilentSys commented on connections/debug/debug_connection.py
> +                full_arr.extend(self.event_mock_set_values())
```suggestion
                # full_arr.extend(self.event_mock_set_values())
```
Let's keep this commented out for now to reduce spam in the UI.

2021-01-19 05:59 UTC, SilentSys commented on main_window/data_entry_id.py
> +    STATE_CRITICAL_FAILURE = auto()
Technically these are for "status" not "state"
```suggestion
    STATUS_NOMINAL = auto()
    STATUS_NONCRITICAL_FAILURE = auto()
    STATUS_CRITICAL_FAILURE = auto()
```

2021-01-19 05:59 UTC, SilentSys commented on main_window/packet_parser.py
> +        data[DataEntryIds.EVENT] = data_entry_value.value
The pythonic way of using enums (especially those with auto values) is without the `.value`. We also need that to discern between enum values and float/numeric values when we handle the data.
```suggestion
        data[DataEntryIds.EVENT] = data_entry_value
```

2021-01-19 05:59 UTC, SilentSys commented on tests/integration_tests/test_debug.py
> +                                                DataEntryIds.EVENT) == DataEntryValues.EVENT_ARMED.value
As per the other comment.
```suggestion
                                                DataEntryIds.EVENT) == DataEntryValues.EVENT_ARMED
```

2021-01-19 05:59 UTC, SilentSys commented on tests/integration_tests/test_sim.py
> +        assert sim_app.rocket_data.last_value_by_device(device_type, DataEntryIds.EVENT) == DataEntryValues.EVENT_DISARMED.value
As per the other comment.
```suggestion
        assert sim_app.rocket_data.last_value_by_device(device_type, DataEntryIds.EVENT) == DataEntryValues.EVENT_ARMED

        sim_app.send_command(device_type.name + ".disarm")
        flush_packets(sim_app, device_type)

        assert sim_app.rocket_data.last_value_by_device(device_type, DataEntryIds.STATE) == 0
        assert sim_app.rocket_data.last_value_by_device(device_type, DataEntryIds.EVENT) == DataEntryValues.EVENT_DISARMED
```

2021-01-19 06:19 UTC, SilentSys commented on main_window/data_entry_id.py
> +    STATE_CRITICAL_FAILURE = auto()
CI is failing. This still needs to be renamed somewhere else in the code.

2021-01-19 18:14 UTC, SilentSys approved these changes
LGTM!

2021-01-24 21:16 UTC, DSep approved these changes
LGTM 👍

2021-01-24 21:39 UTC, DSep requested changes
It seems like the GS never actually receives an event subpacket, as a result of the arm command.  Not sure if FW or send/receive issue on GS.

2021-01-24 21:39 UTC, DSep commented on tests/integration_tests/test_sim.py
> +        assert sim_app.rocket_data.last_value_by_device(device_type, DataEntryIds.EVENT) == DataEntryValues.EVENT_ARMED
I jumped the gun it seems; the SIM arming test (test_arming) is actually failing on this assertion. All other tests pass.

2021-01-24 21:45 UTC, DSep approved these changes

2021-02-02 04:41 UTC, SilentSys commented
CI failed due to a possible known instability. I initiated a re-run.

2021-02-05 05:40 UTC, merged

2021-02-17 19:33 UTC, SilentSys commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Event handling in Packet Parsers and general GS usage](https://trello.com/c/IEFftNFs/277-implement-event-handling-in-packet-parsers-and-general-gs-usage)